# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b45b6f1d7dbb000264d5ef26106bfbc2274045d57e96c88f290d2c6ef29485002102953d1c7cc532e752dfb9fd66338795d942667c37d6b7150e47b144fb081

test:
  secret_key_base: fda918490602f3b6428627cc2c31dcef656d1db12359c79043cc8ab831fb32a8ac183a2020321b20b8600a4fcedd926558a12b232ea8873d37e394d88172fc1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
